### ISSUE TITLE
Search doesn't work at all

### ISSUE THREAD

**Issue by MaroEldawwy6** [corpnewt/ProperTree#178]
When i search for any kind of data in the plist file (Key, String or whatever), the search doesn't show me any result.
And if there is duplicate results in front of my eyes, the search doesn't move between them.

I have the latest version (0.2.9) and Python 2.7.18 on macOS Monterey 12.7.4.

I didn't try other options like "OC Snapshot" or the clean one.

Thanks in advance.

**Comment by corpnewt** [comment]
Can you try with [this commit](https://github.com/corpnewt/ProperTree/commit/8bf14b25cbc80f0dd5c10fa55766a6e3e463e83d)?  I recently migrated a bunch of functions to use deques instead of lists - but it seems that `deque.index()` doesn't exist in python 2, so I've cast any deque instances within the search functions to lists.

**Comment by MaroEldawwy6** [comment]
Works perfectly.

Thank you, @corpnewt

**Comment by corpnewt** [comment]
Glad to hear it - thanks for letting me know!
