### ISSUE TITLE
Newlines in plist go beyond text box

### ISSUE THREAD

**Issue by Sooly890** [corpnewt/ProperTree#187]
Newlines in the plist will go beyond the text box - so for example:

```
			<key>
PciRoot(0x0)/Pci(0x3,0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
</key>
```
Will look like:
![image](https://github.com/user-attachments/assets/1a4a91a5-bf84-47f5-b6ac-74fc40c9d98a)
and when editing:
![image](https://github.com/user-attachments/assets/e375560b-4427-44d7-9673-df97ee48fe1b)
Is this an error on the plist's side or ProperTree's side? I feel like plists should be allowed newlines.
Python 3.8.10 (updated to Python 3.12.7 - issue is still there), Windows 11 24H2

**Comment by corpnewt** [comment]
Yeah - that has to do with the way I create the new floating Entry widges over the tree view.  I'm sure there's a way to get it to resize with the contents, but I haven't explored it much since newlines in plists are somewhat rare (though accepted per the spec).  I should see how Xcode handles them and try to mimic that I suppose.  No ETA on when this will be addressed as it's pretty low priority overall.  Thanks for reminding me about it though!

-CorpNewt

**Comment by corpnewt** [comment]
I just checked in Xcode and it seems to handle newlines the same way:
![image](https://github.com/user-attachments/assets/e438d24a-9b43-4983-bedc-b15c62fe3438)
![image](https://github.com/user-attachments/assets/f5232910-386d-40c3-be05-7044ae553d5e)

I suppose I'll probably leave ProperTree's approach as-is since already matches.  Perhaps I'll look into it later just to give more flexibility - but for now, if it's not an issue in Xcode, I don't think it's something that really needs addressing in ProperTree.

-CorpNewt
