### ISSUE TITLE
Saving plist files restores windows' state

### ISSUE THREAD

**Issue by maroeldawwyp** [corpnewt/ProperTree#189]
Saving plist files after editing restores app windows to its' state.

When snapping a ProperTree window to any edge of screen (on Windows of course), then saving the opened file, the window restores itself to it's previous state (location and size on the screen).

**Comment by corpnewt** [comment]
Hey there - so, when snapped in Windows, if you save, it reverts to the pre-snapped size and position?  I'm not sure if that's something I can change as it sounds like potentially a tkinter issue.  I'll do some digging though.

-CorpNewt

**Comment by corpnewt** [comment]
I just pushed a commit that seemed to work okay for me [here](https://github.com/corpnewt/ProperTree/commit/243065bfc11d0e97f46bc44ad975d97c30846388), if you wouldn't mind testing.

-CorpNewt

**Comment by maroeldawwyp** [comment]
OK, BRB to you...

**Comment by maroeldawwyp** [comment]
Excellent, CorpNewt.

Good job and thanks a lot for fixing this issue, it was super annoying to me, especially when i opened multiple plist files.

**Comment by corpnewt** [comment]
It seems the issue was that I was running `deiconify()` on non-`iconic` windows - essentially "un-minimizing" them when they weren't minimized.  The commit just checks whether or not the window is minimized, and only runs `deiconify()` it if it is.

I'm glad to hear it's fixed now though - and that shouldn't break any of the other functionlity.

-CorpNewt

**Comment by maroeldawwyp** [comment]
Confirmed.

All other fixes (especially the previous Caps-Lock fix) is work as expected.
