### ISSUE TITLE
Save creates empty plist and spawns error in terminal under linux

### ISSUE THREAD

**Issue by belgrid** [corpnewt/ProperTree#22]
Saving a plist under linux creates an empty plist and throws the errors: 

`TypeError: expected bytes, str found
Exception ignored in: 'plist.native_to_plist_t'
Traceback (most recent call last):
  File "/home/mario/Schreibtisch/ProperTree-master/Scripts/plistwindow.py", line 1407, in save_plist_as
    plist_text = plist.dumps(plist_data,sort_keys=self.controller.settings.get("sort_dict",False))
TypeError: expected bytes, str found
TypeError: expected bytes, str found
Exception ignored in: 'plist.create_dict_plist'
Traceback (most recent call last):
  File "/home/mario/Schreibtisch/ProperTree-master/Scripts/plistwindow.py", line 1407, in save_plist_as
    plist_text = plist.dumps(plist_data,sort_keys=self.controller.settings.get("sort_dict",False))
TypeError: expected bytes, str found`

OS: Linux (Arch)
Python 3.8.2

Works fine under Windows.

**Comment by corpnewt** [comment]
Yep - that issue was discussed [here](https://github.com/corpnewt/ProperTree/issues/19) - it seems that `libplist`, which Arch-based linux leverages when using python 3, and python's plistlib module don't interact properly.  You can work around it by using python 2 instead.  But it's ultimately outside the scope of this repo.

-CorpNewt

**Comment by belgrid** [comment]
Thanks for pointing this out!
