### ISSUE TITLE
Clean snapshot command adds plugins inside of kexts on top of the main kext

### ISSUE THREAD

**Issue by zearp** [corpnewt/ProperTree#51]
I'm not sure if this intended or not but when using the clean snapshot command it ads plugins inside of kexts. For example the AirportBrcmFixup.kext will get extra entries added instead of just the base kext and executable. I think it should be up to the kext to load its plugins, not load them all in the config itself. Hope this makes sense, I've attached a picture that illustrates it better than I can explain.

![Screenshot 2020-09-30 at 01 25 47](https://user-images.githubusercontent.com/63272687/94626741-f9eb0100-02bb-11eb-8db3-fd3a4872e237.png)

**Comment by corpnewt** [comment]
If you don't include the plugins in the config.plist, they won't load on their own.  You have to declare all plugins explicitly - as well as load order.   ProperTree attempts to verify the load order and kext integrity via the Info.plist for each kext and ensuring that all kexts that are depended on are loaded before those that depend on them.

This is by design, and required for functionality.

-CorpNewt

**Comment by zearp** [comment]
Ohh, that makes sense. I falsely assumed kexts would load their own plugins. Thank you for clarifying!
